### Recuperar todos los Wabys
GET http://localhost:3000/api/v1/wabys

### Recuperar un Waby
GET http://localhost:3000/api/v1/wabys/1

### Crear un Waby
POST http://localhost:3000/api/v1/wabys
Content-Type: application/json

{
  "nombre": "Juddith Doe",
  "mail": "juddithdoe@gmail.com",
  "peso": 50,
  "altura": 1.50,
  "fechaNacimiento": "2000-12-10",
  "contraseña": "wearewabys123",
  "tipoEntrenamiento": "Calistenia"
}