### Recuperar todos los users
GET http://localhost:3000/api/v1/users

### Recuperar un Waby
GET http://localhost:3000/api/v1/users/1

### Crear un Waby
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Toji Fushiguro",
  "mail": "makidiving@gmail.com",
  "weight": 90,
  "height": 1.90,
  "dateBorn": "2000-12-10",
  "password": "weareusers123",
  "trainingType": "Calistenia"
}

### Actualizar un Waby
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "weight": 85,
  "trainingType": "Calistenia"
}

### Eliminar un Waby
DELETE http://localhost:3000/api/v1/users/3



