### Recuperar todos los Wabys
GET http://localhost:3000/users

### Recuperar un Waby
GET http://localhost:3000/users/1

### Crear un Waby
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "tojiGOAT",
  "password": "elsp2456f62",
  "email": "tojifushiguro@gmail.com",
  "name": "Toji Fushiguro",
  "birthday": "1999-12-22",
  "phone": "1234567890",
  "bodyWeight": 80,
  "height": 1.80,
  "trainingMethod": "Calisthenics"
}

### Actualizar un Waby
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "bodyWeight": 85,
  "trainingMethod": "Calisthenics"
}

### Eliminar un Waby
DELETE http://localhost:3000/users/6

### Recuperar todos los Exercises
GET http://localhost:3000/exercises

### Recuperar un Exercise
GET http://localhost:3000/exercises/3

### Crear un Exercise
POST http://localhost:3000/exercises
Content-Type: application/json


  {
    "idExercise": "3",
    "name": "Pull-up",
    "description": "The pull-up is a compound exercise that primarily targets the muscles of the back",
    "Training": {},
    "trainingMethod": "Calisthenics",
    "muscleGroups": [
            {
                    "idMuscleGroup": "6",
                    "nameMuscleGroup": "Back",
                    "description": ""
            },
            {
                    "idMuscleGroup": "7",
                    "nameMuscleGroup": "Biceps",
                    "description": ""
            }
    ],
    "difficulty": "intermediate",
    "typeExercise": ""
}
